### ISSUE TITLE
Service cannot start anymore

### ISSUE THREAD

**Issue by tio-trom** [YunoHost-Apps/nitter_ynh#27]
I rebooted the server and I get this:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 494, in process
    ret = self.actionsmap.process(arguments, timeout=30, route=_route)
  File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 599, in process
    return func(**arguments)
  File "/usr/lib/moulinette/yunohost/service.py", line 555, in service_log
    result[log_path] = _tail(log_path, number)
  File "/usr/lib/moulinette/yunohost/service.py", line 817, in _tail
    lines = f.read().splitlines()
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 22577: invalid start byte

```

The service cannot start.

**Comment by Jules-Bertholet** [comment]
This looks like it might be a YunoHost problem? Try restarting from the command line with `sudo systemctl restart nitter`, and post any error messages from that

**Comment by tio-trom** [comment]
Ok I restarted it manually and for now it seems to work. I got no error message when I restarted it.

**Comment by tio-trom** [comment]
Same error I see again.... 502 Bad Gateway. I wonder if this is YNH related and how to test and debug,
